spring.application.name=projeto_prog_II
spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.datasource.url=jdbc:h2:mem:alunosdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=ediene
spring.datasource.password=vulneravel

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true